package com.me.nav.vvo.model

data class FlightModel (
    var status_en: String,
    var terminal: String,
    var bort_number: String,
    var stay_number: String,
    var date_and_time_plan: String,
    var date_and_time_calc: String,
    var date_and_time_fact: String,
    var delay_time: String,
    var src_port_cod: String,
    var dest_port_cod: String,
    var etd: String,
    var eta: String,
    var period_start: String,
    var period_end: String,
    var days: String,
    var checkin_desk: String,
    var checkin_begin: String,
    var checkin_end: String,
    var resources: String,
    var reys_num: Any,
    var reys_Comb: String,
    var aircompany_Comb: String,
    var aircompany: Any,
    var aircompany_ext: String,
    var status: String,
    var litera: String,
    var typevs_code: String,
    var type: String,
    var view: String,
    var delay_code: String,
    var src_city: String,
    var dest_city: String,
    var src_port: String,
    var dest_port: String,
    var path: String
)